[2025-05-06T12:58:05.376+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mask_pii.mask manual__2025-05-06T12:58:03.021858+00:00 [queued]>
[2025-05-06T12:58:05.381+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mask_pii.mask manual__2025-05-06T12:58:03.021858+00:00 [queued]>
[2025-05-06T12:58:05.381+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-05-06T12:58:05.390+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): mask> on 2025-05-06 12:58:03.021858+00:00
[2025-05-06T12:58:05.394+0000] {standard_task_runner.py:57} INFO - Started process 1242 to run task
[2025-05-06T12:58:05.396+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'mask_pii', 'mask', 'manual__2025-05-06T12:58:03.021858+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/mask_pii.py', '--cfg-path', '/tmp/tmpw2103gju']
[2025-05-06T12:58:05.396+0000] {standard_task_runner.py:85} INFO - Job 193: Subtask mask
[2025-05-06T12:58:05.407+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-06T12:58:05.433+0000] {task_command.py:410} INFO - Running <TaskInstance: mask_pii.mask manual__2025-05-06T12:58:03.021858+00:00 [running]> on host 016737cbcc7e
[2025-05-06T12:58:05.491+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mask_pii' AIRFLOW_CTX_TASK_ID='mask' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T12:58:03.021858+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T12:58:03.021858+00:00'
[2025-05-06T12:58:05.492+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-06T12:58:05.492+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-06T12:58:05.508+0000] {logging_mixin.py:150} INFO - Загружено 1200 клиентов для маскирования
[2025-05-06T12:58:05.566+0000] {logging_mixin.py:150} INFO - Маскированные данные клиентов сохранены в raw.masked_clients
[2025-05-06T12:58:05.601+0000] {logging_mixin.py:150} INFO - Загружено 4652 транзакций для маскирования
[2025-05-06T12:58:05.810+0000] {logging_mixin.py:150} INFO - Маскированные данные транзакций сохранены в raw.masked_transactions
[2025-05-06T12:58:05.811+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-06T12:58:05.818+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=mask_pii, task_id=mask, execution_date=20250506T125803, start_date=20250506T125805, end_date=20250506T125805
[2025-05-06T12:58:05.849+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-05-06T12:58:05.877+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
