[2025-04-27T11:53:16.305+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform.detect_suspicious manual__2025-04-27T11:09:48.374618+00:00 [queued]>
[2025-04-27T11:53:16.311+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform.detect_suspicious manual__2025-04-27T11:09:48.374618+00:00 [queued]>
[2025-04-27T11:53:16.312+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-04-27T11:53:16.322+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): detect_suspicious> on 2025-04-27 11:09:48.374618+00:00
[2025-04-27T11:53:16.325+0000] {standard_task_runner.py:57} INFO - Started process 54 to run task
[2025-04-27T11:53:16.327+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'transform', 'detect_suspicious', 'manual__2025-04-27T11:09:48.374618+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/transform.py', '--cfg-path', '/tmp/tmphuhfysvu']
[2025-04-27T11:53:16.328+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask detect_suspicious
[2025-04-27T11:53:16.365+0000] {task_command.py:410} INFO - Running <TaskInstance: transform.detect_suspicious manual__2025-04-27T11:09:48.374618+00:00 [running]> on host 6780dda4d52a
[2025-04-27T11:53:16.498+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='finbest' AIRFLOW_CTX_DAG_ID='transform' AIRFLOW_CTX_TASK_ID='detect_suspicious' AIRFLOW_CTX_EXECUTION_DATE='2025-04-27T11:09:48.374618+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-27T11:09:48.374618+00:00'
[2025-04-27T11:53:16.506+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-27T11:53:16.507+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --packages org.postgresql:postgresql:42.6.0,ru.yandex.clickhouse:clickhouse-jdbc:0.3.2 --executor-cores 1 --executor-memory 1g --driver-memory 1g --name arrow-spark /opt/airflow/spark/detect_suspicious.py --jdbc jdbc:postgresql://postgres:5432/finbest --clickhouse-url jdbc:clickhouse://clickhouse:8123/finbest
[2025-04-27T11:53:18.532+0000] {spark_submit.py:490} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-04-27T11:53:18.636+0000] {spark_submit.py:490} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-04-27T11:53:18.636+0000] {spark_submit.py:490} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-04-27T11:53:18.643+0000] {spark_submit.py:490} INFO - org.postgresql#postgresql added as a dependency
[2025-04-27T11:53:18.643+0000] {spark_submit.py:490} INFO - ru.yandex.clickhouse#clickhouse-jdbc added as a dependency
[2025-04-27T11:53:18.644+0000] {spark_submit.py:490} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-49b85f70-f73c-4547-9e13-c841db57fe35;1.0
[2025-04-27T11:53:18.646+0000] {spark_submit.py:490} INFO - confs: [default]
[2025-04-27T11:53:22.357+0000] {spark_submit.py:490} INFO - found org.postgresql#postgresql;42.6.0 in central
[2025-04-27T11:53:22.835+0000] {spark_submit.py:490} INFO - found org.checkerframework#checker-qual;3.31.0 in central
[2025-04-27T11:53:23.877+0000] {spark_submit.py:490} INFO - found ru.yandex.clickhouse#clickhouse-jdbc;0.3.2 in central
[2025-04-27T11:53:24.991+0000] {spark_submit.py:490} INFO - found com.clickhouse#clickhouse-http-client;0.3.2 in central
[2025-04-27T11:53:26.115+0000] {spark_submit.py:490} INFO - found com.clickhouse#clickhouse-client;0.3.2 in central
[2025-04-27T11:53:26.938+0000] {spark_submit.py:490} INFO - found org.lz4#lz4-java;1.8.0 in central
[2025-04-27T11:53:32.430+0000] {spark_submit.py:490} INFO - found com.google.code.gson#gson;2.8.8 in central
[2025-04-27T11:53:36.570+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-04-27T11:53:36.571+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 54. PIDs of all processes in the group: [55, 54]
[2025-04-27T11:53:36.571+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 54
[2025-04-27T11:53:36.572+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-27T11:53:36.572+0000] {spark_submit.py:615} INFO - Sending kill signal to spark-submit
[2025-04-27T11:53:36.584+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 409, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 458, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-04-27T11:53:36.588+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=transform, task_id=detect_suspicious, execution_date=20250427T110948, start_date=20250427T115316, end_date=20250427T115336
[2025-04-27T11:53:36.599+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 68 for task detect_suspicious (Task received SIGTERM signal; 54)
[2025-04-27T11:53:36.623+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=55, status='terminated', started='11:53:16') (55) terminated with exit code None
[2025-04-27T11:53:36.624+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=54, status='terminated', exitcode=1, started='11:53:16') (54) terminated with exit code 1
