[2025-05-09T22:05:37.949+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superset_sync.create_superset_dataset manual__2025-05-09T22:05:35.807744+00:00 [queued]>
[2025-05-09T22:05:37.954+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superset_sync.create_superset_dataset manual__2025-05-09T22:05:35.807744+00:00 [queued]>
[2025-05-09T22:05:37.954+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-05-09T22:05:37.962+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_superset_dataset> on 2025-05-09 22:05:35.807744+00:00
[2025-05-09T22:05:37.966+0000] {standard_task_runner.py:57} INFO - Started process 24245 to run task
[2025-05-09T22:05:37.968+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'superset_sync', 'create_superset_dataset', 'manual__2025-05-09T22:05:35.807744+00:00', '--job-id', '425', '--raw', '--subdir', 'DAGS_FOLDER/superset_sync.py', '--cfg-path', '/tmp/tmpy6u_bv5k']
[2025-05-09T22:05:37.968+0000] {standard_task_runner.py:85} INFO - Job 425: Subtask create_superset_dataset
[2025-05-09T22:05:37.979+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-09T22:05:38.003+0000] {task_command.py:410} INFO - Running <TaskInstance: superset_sync.create_superset_dataset manual__2025-05-09T22:05:35.807744+00:00 [running]> on host d3632ec65b22
[2025-05-09T22:05:38.060+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='superset_sync' AIRFLOW_CTX_TASK_ID='create_superset_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T22:05:35.807744+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T22:05:35.807744+00:00'
[2025-05-09T22:05:38.357+0000] {superset_sync.py:83} INFO - Dataset уже есть (id=1)
[2025-05-09T22:05:38.439+0000] {python.py:183} INFO - Done. Returned value was: 1
[2025-05-09T22:05:38.460+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=superset_sync, task_id=create_superset_dataset, execution_date=20250509T220535, start_date=20250509T220537, end_date=20250509T220538
[2025-05-09T22:05:38.501+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-05-09T22:05:38.529+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
